config/routes.rb
Rails.application.routes.draw do
  resources :my_teams
  resources :players do
    resources :notes
  end
  root "players#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  has_many :notes
end

app/models/user.rb
class User < ApplicationRecord
  has_many :players
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_player

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.player = @player
    # @note.user = current_user

    respond_to do |format|
      if @note.save
        format.html { redirect_to [@player, @note], notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to [@player, @note], notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to player_notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    def set_player
      @player = Player.find(params[:player_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.fetch(:note, {}).permit(:subject, :body)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = current_user.players.build
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = current_user.players.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.fetch(:player, {}).permit(:name, :position, :team, :owner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FantasyPlayerNotes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <li>
        <% logged_in = current_user.email %>
        <%= logged_in %>
      </li>
      <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      </li>
    <% else %>
      <li>
      <%= link_to('Login', new_user_session_path) %>
      </li>
    <% end %> 
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: [player, note], local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.label :subject %>
    <%= form.text_field :subject, size: "30x1" %>

    <%= form.label :body %>
    <%= form.text_area :body , size: "30x10" %>

    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', player: @player, note: @note %>

<%= link_to 'Show', [@player, @note] %> |
<%= link_to 'Back', player_notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<% header = @player.name + ' Player Notes' %>
<h1><%= header %></h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><strong>Date</strong></td>
      <td><strong>Subject</strong></td>
    </tr>
    <% @notes.order("created_at DESC").each do |note| %>
      <% if note.player_id == @player.id %>
        <tr>
          <td><%= note.created_at.strftime("%m-%d-%Y") %>
          <td><%= note.subject %>
          <td><%= link_to 'Show', player_note_path(note.player, note) %></td>
          <td><%= link_to 'Edit', edit_player_note_path(note.player, note) %></td>
          <td><%= link_to 'Destroy', [note.player, note], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Note', new_player_note_path %></p>
<p><%= link_to 'Return to Player Page', player_path(@player) %></p>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', player: @player, note: @note %>

<%= link_to 'Back', player_path(@player) %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @note.subject%></h1>

<body>
    <p><%= @note.created_at.strftime('%m-%d-%Y') %></p>
    <p><%= @note.body %></p>
</body>

<br />
<br />

<footer>
    <%= link_to 'Edit', edit_player_note_path(@note) %> |
    <%= link_to 'Back', player_notes_path %>
</footer>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :position %>
    <% positions = [["QB"], ["RB"], ["WR"], ["TE"], ["K"], ["D/ST"]] %>
    <%= form.select(:position, positions, {}, {:multiple => false}) %>

    <%= form.label :team %>
    <% teams = [["ARI"], ["ATL"], ["BAL"], ["BUF"], ["CAR"], ["CHI"], ["CIN"], ["CLE"], ["DAL"], ["DEN"], ["DET"], ["GB"], ["HOU"], ["IND"], ["JAX"], ["KC"], ["MIA"], ["MIN"], ["NE"], ["NO"], ["NYG"], ["NYJ"], ["OAK"], ["PHI"], ["PIT"], ["SD"], ["SEA"], ["SF"], ["STL"], ["TB"], ["TEN"], ["WAS"]] %>
    <%= form.select(:team, teams, {}, {:multiple => false}) %>

    <%= form.label :owner %>
    <%= form.text_field :owner %>

    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody align="left">
      <tr>
        <th>Name</th>
        <th>Position</th>
        <th>Team</th>
        <th>Owner</th>
      </tr>
    <% @players.each do |player| %>
      <% if current_user && player.user_id == current_user.id %>
        <tr>
          <td><%= player.name %></td>
          <td><%= player.position %></td>
          <td><%= player.team %></td>
          <td><%= player.owner %></td>
          <td><%= link_to 'Show', player %></td>
          <td><%= link_to 'Edit', edit_player_path(player) %></td>
          <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%=@player.name%></h1>
<h2><%=@player.position%></h2>
<h2><%=@player.team%></h2>
<h2><%=@player.owner%></h2>

<p><%= link_to 'View Notes', player_notes_path(@player) %></p>

<p><%= link_to 'New Note', new_player_note_path(@player) %></p>

<p><%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Return to Player List', players_path %>
</p>